In [ ]:
***numpy arrays***


In [1]:
import numpy as np
#create 1 D array
array_1D=np.array([1,2,3,4,5])
print("1 D array is : ",array_1D)

1 D array is :  [1 2 3 4 5]


In [2]:
#2 D array
array_2D=np.array([[1,2,3],[4,5,6]])
print(array_2D)

[[1 2 3]
 [4 5 6]]


In [3]:
#3D array
array_3D=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(array_3D)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [5]:
#create an array with once
array_ones=np.ones((2,4))
print("Array with ones : ",array_ones)

Array with ones :  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
#create array with zeros
array_zeros=np.zeros((3,3))
print(array_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
#create an array with a particular range
array_range=np.arange(10)
print(array_range)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
#Access element with in the array
array_2D=np.array([[1,2,3],[4,5,6]])
element=array_2D[1,2]
print(element)

6


In [9]:
#Access element with in the array
array_2D=np.array([[1,2,3],[4,5,6]])
element=array_2D[0,1]
print(element)

2


In [17]:
#Access by 2row
row=array_2D[1,:]
print(row)

[4 5 6]


In [13]:
#Access by 2row
row=array_2D[0,:]
print(row)

[1 2 3]


In [15]:
#Access the 2nd column
column=array_2D[:,1]
print(column)


[2 5]


In [18]:
#slicing
slice_array=array_2D[0:2,1:3]
print(slice_array)

[[2 3]
 [5 6]]


In [19]:
#view and copy
orginal_array=np.array([1,2,3,4,5,6])
print(orginal_array)

[1 2 3 4 5 6]


In [21]:
#create a view for the array
view_array=orginal_array.view()
print(view_array)

[1 2 3 4 5 6]


In [22]:
view_array[2]=30
print(view_array)

[ 1  2 30  4  5  6]


In [23]:
print(orginal_array)

[ 1  2 30  4  5  6]


In [24]:
#create a copy of orgianl array
copy_array=orginal_array.copy()
print(copy_array)

[ 1  2 30  4  5  6]


In [25]:
copy_array[0]=10
print(copy_array)

[10  2 30  4  5  6]


In [26]:
print(orginal_array)

[ 1  2 30  4  5  6]
