In [1]:
# 1. Print the shape of a 2-D array
import numpy as np
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d.shape)

(2, 3)


In [2]:
# 2.  Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4

import numpy as np
arr_5d = np.array([1, 2, 3, 4], ndmin=5)
print("Shape of the array:", arr_5d.shape)
print("Last dimension size:", arr_5d.shape[-1])

Shape of the array: (1, 1, 1, 1, 4)
Last dimension size: 4


In [3]:
#3. Convert the following 1-D array with 12 elements into a 2-D array. The outermost dimension will have 4 arrays, each with 3 elements:
import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr_2d = arr_1d.reshape(4, 3)
print(arr_2d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
#4. Convert the following 1-D array with 12 elements into a 3-D array. The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements
import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr_3d = arr_1d.reshape(2, 3, 2)
print(arr_3d)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [5]:
#5. Check if the returned array is a copy or a view.
import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr_3d = arr_1d.reshape(2, 3, 2)
is_view = arr_3d.base is arr_1d             

print("Is the reshaped array a view?", is_view)

Is the reshaped array a view? True
