In [ ]:
****How do you create a NumPy array****

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
****How do you create an array filled with zeros****

In [2]:
zeros_array = np.zeros((3, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
****How do you create an array with a range of numbers****

In [3]:
range_array = np.arange(0, 10, 2) 
print(range_array)


[0 2 4 6 8]


In [ ]:
****How do you create an array of evenly spaced values****

In [5]:
linspace_array = np.linspace(0, 1, 5)
print(linspace_array)


[0.   0.25 0.5  0.75 1.  ]


In [ ]:
****How do you create an identity matrix****

In [6]:
identity_matrix = np.eye(3) 
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
****How do you reshape an array****

In [7]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape((2, 3))
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
****How do you get the shape of an array****

In [8]:
shape = arr.shape
print(shape)


(6,)


In [ ]:
****How do you perform element-wise addition on two arrays****

In [9]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result)

[5 7 9]


In [ ]:
****How do you find the maximum value in an array****

In [10]:
max_value = arr.max()
print(max_value)

6


In [ ]:
****How do you compute the mean of an array****

In [11]:
mean_value = arr.mean()
print(mean_value)

3.5


In [ ]:
****How do you generate random numbers in NumPy****

In [12]:
random_numbers = np.random.rand(5) 
print(random_numbers)


[0.70495745 0.7371563  0.68035982 0.97810582 0.26878602]


In [ ]:
****How do you sort an array****

In [13]:
sorted_arr = np.sort(arr)
print(sorted_arr)

[1 2 3 4 5 6]


In [ ]:
****How do you get the transpose of a matrix****

In [14]:
matrix = np.array([[1, 2], [3, 4]])
transposed_matrix = matrix.T
print(transposed_matrix)

[[1 3]
 [2 4]]


In [ ]:
****How do you flatten a multi-dimensional array****

In [15]:
flat_array = arr.flatten()
print(flat_array)

[1 2 3 4 5 6]


In [ ]:
****How do you find the index of the maximum value in an array****

In [16]:
index_max = arr.argmax()
print(index_max)

5


In [ ]:
****Create a NumPy Array and Convert to pandas DataFrame****

In [1]:
import numpy as np
import pandas as pd

array = np.arange(10)
df = pd.DataFrame(array, columns=['Numbers'])
print(df)


   Numbers
0        0
1        1
2        2
3        3
4        4
5        5
6        6
7        7
8        8
9        9


In [ ]:
**Create a DataFrame with columns 'A' and 'B' and calculate the mean of column 'A' using NumPy**

In [2]:
df = pd.DataFrame({'A': [1, 2, 3, 4, 5], 'B': [10, 20, 30, 40, 50]})
mean_A = np.mean(df['A'])
print(mean_A)


3.0
