In [ ]:
****Reshaping****

In [ ]:
*****reshape() is the method to convert 1D to 2D,2D to 3D..........*****

In [2]:
import numpy as np
#create 1D array
array_1=np.array([1,2,3,4,5,6])
print(array_1)
print(array_1.shape)


[1 2 3 4 5 6]
(6,)


In [6]:
#convert to 2D(reshape the array(means 1D to 2D))
array_2d=array_1.reshape((2,3))
print(array_2d)
print(array_2d.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [8]:
import numpy as np
#create 1D array
array_1=np.array([1,2,3,4,5,6,7,8,9])
print(array_1)
print(array_1.shape)
#convert to 3D array
array_3d=array_1.reshape((3,3))
print(array_3d)
print(array_3d.shape)

[1 2 3 4 5 6 7 8 9]
(9,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [ ]:
convert 2d array back to 1d array

In [19]:
d1_back=array_2d.reshape(1,6)
print(d1_back)
print(d1_back.shape)

[[1 2 3 4 5 6]]
(1, 6)


In [20]:
d1_back=array_2d.reshape(-1)
print(d1_back)
print(d1_back.shape)

[1 2 3 4 5 6]
(6,)


In [ ]:
******iteration******

In [ ]:
*******how we can do iterations*****

In [22]:
array_1d=np.array([1,2,3,4,5,6,7,8,9,10])
print(array_1d)
for elements in array_1d:
    print(elements)

[ 1  2  3  4  5  6  7  8  9 10]
1
2
3
4
5
6
7
8
9
10


In [26]:
array_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array_2d)
for rows in array_2d:
    print(rows)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[4 5 6]
[7 8 9]


In [29]:
array_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array_2d)
for elements in np.nditer(array_2d):
    print(elements)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
3
4
5
6
7
8
9


In [30]:
#iterate the elements with index
for index,element in np.ndenumerate(array_2d):
    print(index,element)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 9


In [35]:
#join of two array
array1=np.array([1,2,3])
array2=np.array([4,5,6])
array=np.concatenate((array1,array2))
print(array)

[1 2 3 4 5 6]


In [39]:
array2d1=np.array([[1,2,3],[4,5,6]])
array2d2=np.array([[7,8,9],[10,11,12]])
concate2d=np.concatenate((array2d1,array2d2))
print(concate2d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [40]:
#join vertically
vstack_array=np.vstack((array2d1,array2d2))
print(vstack_array)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [41]:
#join horizontally
hstack_array=np.hstack((array2d1,array2d2))
print(hstack_array)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
****split will work in numpy****

In [42]:
array=np.array([1,2,3,4,5,6,7,8,9])
split_array=np.split(array,3)
print(array)
print(split_array)

[1 2 3 4 5 6 7 8 9]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [ ]:
***splitting horizontaly and vertically multidimensional array***

In [50]:
array_2d=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
vsplit_array=np.vsplit(array_2d,2)
print(vsplit_array)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]


In [48]:
#check
import numpy as np
array=np.array([10,20,12,15,14,17])
#element grater than 15 for the above array
elements=np.where(array>15)
print(array[elements])

[20 17]


In [52]:
#check
import numpy as np
array=np.array([10,20,12,15,14,17])
#element grater than 15 for the above array
elements=np.where(array>15,0,array)
print(elements)

[10  0 12 15 14  0]
