In [7]:
#How to create an empty and a full NumPy array?
import numpy as np

# Create an empty array of shape (3, 3)
empty_array = np.empty((3, 3))

print("Empty array:")
print(empty_array)


Empty array:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:

# Create a full array of shape (3, 3) with all elements set to 1
full_array = np.full((3, 3), 1)

print("Full array:")
print(full_array)


Full array:
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
**** Find the number of rows and columns of a given matrix using NumPy******

In [6]:
import numpy as np


matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Get the shape of the matrix
rows, columns = matrix.shape

print(f"Number of rows: {rows}")
print(f"Number of columns: {columns}")


Number of rows: 3
Number of columns: 3


In [ ]:
***Counts the number of non-zero values in the array***

In [1]:
import numpy as np

array = np.array([1, 0, 2, 0, 3, 4, 0, 5])

# Count the number of non-zero values
non_zero_count = np.count_nonzero(array)

print(f"The number of non-zero values in the array is: {non_zero_count}")


The number of non-zero values in the array is: 5


In [ ]:
***Find the sum of values in a matrix***

In [2]:
import numpy as np
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

#  the sum of all values in the matrix
matrix_sum = np.sum(matrix)

print(f"The sum of all values in the matrix is: {matrix_sum}")


The sum of all values in the matrix is: 45


In [ ]:
***Calculate the sum of the diagonal elements of a NumPy array 3*3 and 4*4***

In [14]:
#Calculate the sum of the diagonal elements of a NumPy array 3*3 and 4*4

import numpy as np

matrix_3x3 = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

matrix_4x4 = np.array([[1, 2, 3, 4],
                       [5, 6, 7, 8],
                       [9, 10, 11, 12],
                       [13, 14, 15, 16]])

diagonal_sum_3x3 = np.trace(matrix_3x3)
diagonal_sum_4x4 = np.trace(matrix_4x4)

print("Sum of the diagonal elements of the 3x3 matrix:", diagonal_sum_3x3)
print("Sum of the diagonal elements of the 4x4 matrix:", diagonal_sum_4x4)


Sum of the diagonal elements of the 3x3 matrix: 15
Sum of the diagonal elements of the 4x4 matrix: 34


In [ ]:
***How to inverse a matrix using NumPy***

In [13]:
#3x3 matrix
import numpy as np
matrix_3x3 = np.array([
    [1, 2, 3],
    [0, 1, 4],
    [5, 6, 0]
])

inverse_matrix_3x3 = np.linalg.inv(matrix_3x3)
print("The inverse of the 3x3 matrix is:")
print(inverse_matrix_3x3)


The inverse of the 3x3 matrix is:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


In [ ]:
***Matrix Multiplication in NumPy***


In [15]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.dot(A, B)
print(C)


[[19 22]
 [43 50]]


In [ ]:
***Get the maximum and minimum value from given matrix***

In [16]:
import numpy as np
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
max_value = np.max(matrix)
min_value = np.min(matrix)
print("Maximum value:", max_value)
print("Minimum value:", min_value)

Maximum value: 9
Minimum value: 1


In [ ]:
*** Adding and Subtracting Matrices in Python***

In [18]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
addition_result = A + B
subtraction_result = A - B
print("Addition Result:\n", addition_result)
print("Subtraction Result:\n", subtraction_result)


Addition Result:
 [[ 6  8]
 [10 12]]
Subtraction Result:
 [[-4 -4]
 [-4 -4]]


In [ ]:
***How to count the frequency of unique values in NumPy array***

In [19]:
import numpy as np
arr = np.array([1, 2, 3, 4, 2, 3, 1, 2, 4, 5, 1, 2])
unique_values, counts = np.unique(arr, return_counts=True)
for value, count in zip(unique_values, counts):
    print(f"Value: {value}, Count: {count}")



Value: 1, Count: 3
Value: 2, Count: 4
Value: 3, Count: 2
Value: 4, Count: 2
Value: 5, Count: 1
